"""add other tables

Revision ID: 887275461b9e
Revises: d0e1f2a3b4c5
Create Date: 2026-04-20 14:35:16.845015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887275461b9e'
down_revision: Union[str, Sequence[str], None] = 'd0e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rbac_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['rbac_groups.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rbac_roles', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('rbac_roles', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('rbac_roles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('rbac_roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('rbac_roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'rbac_roles', ['name'])
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK to rbac_roles',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               comment='FK to rbac_roles',
               existing_nullable=True)
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'rbac_roles', type_='unique')
    op.drop_column('rbac_roles', 'deleted_at')
    op.drop_column('rbac_roles', 'updated_at')
    op.drop_column('rbac_roles', 'created_at')
    op.drop_column('rbac_roles', 'description')
    op.drop_column('rbac_roles', 'name')
    op.drop_table('rbac_role_permissions')
    op.drop_table('rbac_permissions')
    op.drop_table('rbac_groups')
    # ### end Alembic commands ###
